# Generated by Django 2.2.11 on 2020-12-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importdata',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='importdata',
            old_name='Phone',
            new_name='phone',
        ),
    ]
